AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: disable
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Lint/Debugger:
  Enabled: false
